image: ros:noetic-ros-core

cache:
  paths:
    - ccache/

before_script:
  - apt update >/dev/null && apt install -y git >/dev/null
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git >/dev/null
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null

catkin_make:
  tags: 
    - linux
  stage: build
  script:
    - catkin_make

catkin tools:
  tags: 
    - linux
  stage: build
  script:
    - catkin build --summarize --no-status --force-color
